### ISSUE TITLE
Missed out requirements on increment 0 but completed increment 1,2,3

### ISSUE THREAD

**Issue by yicheng-toh** [nus-cs2113-AY2324S1/forum#11]
Hi,

I have done level 1,2,3 increment but I have realised I have forgotten to rename my bot (a requirement for increment 0). How do I proceed. Can I change it on increment 3, or do I need to somehow backtrack and edit on increment 0 and then merge it. Or is it too late?

Thanks for advice.

**Comment by okkhoy** [comment]
I am assuming you are using the default name "Duke". If so, just go ahead to rename it now and tag the latest commit that did the renaming as level 0 :-) 
If you are referring to something else, please ping me on MSTeams to explain the situation.
@yicheng-toh
