### ISSUE TITLE
I cannot join the course organization

### ISSUE THREAD

**Issue by wendelinwemhoener** [nus-cs2113-AY2324S1/forum#14]
According to https://nus-cs2113-ay2324s1.github.io/website/schedule/week4/admin.html#1-accept-github-invitation-from-the-course-organization-counted-for-participation, we are supposed to join the cs2113-AY2324S1 Github Organization. 
However, I did not receive an invitation email and the invitation link on the course website (https://github.com/orgs/nus-cs2113-AY2324S1/invitation) also doesn't work.
How am I supposed to join the Github Organization in this case?

**Comment by skylee03** [comment]
The teacher has not issued an invitation yet. We should only be able to join an organization after receiving an invitation.

**Comment by okkhoy** [comment]
I am still waiting for a few students to submit their GitHub usernames 😕. We will send out the invitation once I receive the info from all students.
