### ISSUE TITLE
[iP] Do we still need to support adding ordinary tasks?

### ISSUE THREAD

**Issue by skylee03** [nus-cs2113-AY2324S1/forum#16]
In Week 4, we added support for tracking three types of tasks: ToDos, Events, and Deadlines. However, we are not required to remove the old way of adding ordinary tasks. Therefore, when the user's command is `blah`, we should create a task called `blah`.
In `Level-5` of Week 5, we are asked to handle such input as an exception. Does this mean we need to remove the old way of adding ordinary tasks?

**Comment by okkhoy** [comment]
your old way of creating tasks could still remain if you choose to handle it smartly 😜  (i.e., depending on the rest of the input string you could parse it to event, deadline or retain it as todo); alternatively, you could choose to retain only the behavior for 3 types of tasks and handle everything using exceptions. choice is yours 🙂
