### ISSUE TITLE
Tag and branch show in github but not on ip dashboard

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2113-AY2324S1/forum#18]
As per title, I can find all my tags and branches in github but on ip dashboard it is still marked as not done
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/82555990/0628c6fd-f3d8-4b3a-892c-a592ed616170)

![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/82555990/fc5af073-5bd1-4100-a5b0-d4477cb3059e)

**Comment by DextheChik3n** [comment]
the ip dashboard thingy updates once everyday so u can check tomorrow and it will prolly turn green
there's a text to show when the dashboard was last updated above the table there

**Comment by ziyi105** [comment]
I see, thank you!
