### ISSUE TITLE
runtest.bat not working as expected

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2113-AY2324S1/forum#19]
I have already crtl v ctrl c my actual output on EXPECTED.TXT, but for some reason I can never get the "no differences encountered" output. Anybody has any idea why?

![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/82555990/878d51e3-e907-49a7-8940-cf8296e61bc9)

**Comment by okkhoy** [comment]
this can mostly be due to the line ending. 
1. Please ensure you have git bash available on your machine (if it is Windows)
2. Meet me after the lecture to resolve this issue.

**Comment by ziyi105** [comment]
Hi Prof, I changed all System.out.print() and "\n" to System.out.println() according to your instruction and it's finally working! Thank you
