### ISSUE TITLE
JDK Version

### ISSUE THREAD

**Issue by skylee03** [nus-cs2113-AY2324S1/forum#2]
When configuring projects for the course, can we use a newer version of SDK instead, but set the language level to 11?
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/24489025/73036e9a-5875-4631-a9f2-cebd46c2bc7b)

**Comment by damithc** [comment]
@skylee03 Sure. If you run into version-related issues later, you can change the settings then.
