### ISSUE TITLE
A-JavaDoc, most of my public methods are self-explanatory

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2113-AY2324S1/forum#22]
in that case, do I still need to add comments? If I don't will the marking script mark me down?

**Comment by ziyi105** [comment]
Does commenting in the method count?

**Comment by okkhoy** [comment]
You can explain what the method does in the header comment. 
Commenting inside the method doesn't count as header comment.

**Comment by ziyi105** [comment]
Most of my method names are very straight forward, like addTodo(), getSize(), readFile(), run(), printHelloMessage(), if i comment on them isnt that repeating the obvious?

**Comment by okkhoy** [comment]
hmmm... valid point! the baseline I normally suggest is this: anything other than a getter/setter is a non-trivial method; add comments to all non-trivial methods :-)

**Comment by ziyi105** [comment]
alright, thank you!
