### ISSUE TITLE
Level-8, Replacing String with LocalDate

### ISSUE THREAD

**Issue by StanleyW00** [nus-cs2113-AY2324S1/forum#23]
I'm wondering for this level, do we replace the variables holding from, to, and by, from string to localdate, so that it only accepts a specific date and time format?

**Comment by okkhoy** [comment]
sure! you can do that :-) we leave specific implementation details to you to decide. 
We specify the following:
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/1023494/2e62f6aa-28d8-4c20-b6bf-f0f56faf604d)
However, I'm curious, if not the way you specify, what other approach have you thought about?

**Comment by StanleyW00** [comment]
I'm thinking of making somekind of indicator to specify which type to use when creating a deadline or an event. I believe that the former is simpler and I think it should be faster to implement.

**Comment by okkhoy** [comment]
Think from the user's perspective. Would the user really care if you stored it as a string or a date? 
All the user would want is a way to store the date and time. 🙂

**Comment by StanleyW00** [comment]
Ahhh okay then. Anyway, thank you for answering, prof!
