### ISSUE TITLE
Forgot to branch out level 9 and A-JavaDoc

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2113-AY2324S1/forum#24]
What should I do in this case :(  I tagged my commits for level 9 and A-JavaDoc already

**Comment by okkhoy** [comment]
You can create an appropriate branch and [cherry-pick](https://www.youtube.com/watch?v=2qSSfOQuxvQ) the commits to the new branch.
Then, go on to complete the task per the requirements.

**Comment by ziyi105** [comment]
Ok thank you!
