### ISSUE TITLE
Week 7 Tutorial: Unable to run Duke

### ISSUE THREAD

**Issue by bnjm2000** [nus-cs2113-AY2324S1/forum#25]
Had trouble following the tutorial as I was unable to run Duke.java after forking and cloning to my local machine. Upon opening in IntelliJ, I get an error message of tp: failed and I do not have the option of running Duke

I am running a 2022 Mac M2 Max with MacOS 13.2 (maybe that has something to do with it)

Anyone facing the same issue? Any help would be appreciated. TIA!

<img width="1512" alt="tp failed" src="https://github.com/nus-cs2113-AY2324S1/forum/assets/142559789/ebbe1953-bfa8-4d87-aef8-f19751954e1c">

<img width="1400" alt="Duke" src="https://github.com/nus-cs2113-AY2324S1/forum/assets/142559789/67b4c63c-6be7-4a00-a8e2-5c1adede2185">

**Comment by okkhoy** [comment]
This potentially happens when the JVM gradle uses and your default JVM conflicts.
@exetr can you please post the instructions on how to set the default JVM to Java11?

**Comment by exetr** [comment]
Could I also ask whether you have previously installed different versions of the Java runtime and if so, have you done anything to swap the active version of Java?

If not, you can try the following steps to try to resolve the issue:
1. As a sanity check, could you open a terminal and run `java -version`, verify that the version of Java is set to 11 (adhere to the tP constraints).
2. After opening the project in IntelliJ, click on the settings button near the top right > Project Structure > Project Settings > Project. Under the SDK, ensure that the matching version of Java you saw in step 1 is selected. For "Language Level" ensure that the corresponding version is set.
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/23265811/706e648e-0a14-4a3d-94e2-60f2268568d6)
3. In the same menu, under Platform Settings > SDKs, ensure that there is an entry for the corresponding version of Java.
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/23265811/3b3f48e1-e0cc-44f8-a9f6-2396d46a1c58)
4. Once done, click Apply and OK to close the menu.
5. Check whether IntelliJ has updated the project to detect Java

**Comment by bnjm2000** [comment]
This worked, thank you both so much for your assistance! I can finially upload my screenshots, hope they can still be counted :")
