### ISSUE TITLE
jar file not available under GitHub releases

### ISSUE THREAD

**Issue by Hongzhii** [nus-cs2113-AY2324S1/forum#26]
I was sent an automated email last night saying that my jar file was not available under my releases. However, when I checked the link myself I can see the jar file submitted. Is there a particular format that the GitHub release should be in? 

I have attached a screenshot of the GitHub releases page below.

<img width="1188" alt="Screenshot 2023-10-07 at 9 34 06 AM" src="https://github.com/nus-cs2113-AY2324S1/forum/assets/97496506/827968b6-ca7c-4bf3-9c06-9f207e8f029a">

**Comment by okkhoy** [comment]
We are looking at this link: https://github.com/Hongzhii/ip/releases
I can only see something from 2 weeks ago:
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/1023494/bcb89251-45fa-4630-be49-138e35e97300)

**Comment by okkhoy** [comment]
Hmmm.. go to the releases page (link I sent) and create a release. 
It looks like you have uploaded the JAR to the tag and not made a release
@Hongzhii ☝️

**Comment by Hongzhii** [comment]
It seems that the previous release was visible only when I was logged into GitHub (was not visible when accessing the link in incognito). I created a second release and it seems to have fixed the issue. Is my release visible now?
