### ISSUE TITLE
Test IP jar file for Mac or Linux

### ISSUE THREAD

**Issue by StanleyW00** [nus-cs2113-AY2324S1/forum#27]
Hello,  I have an issue regarding getting input for Mac and Linux for my project and I have modified my code.I have used Windows and I am wondering if anyone willing do a smoke test with my project to see if there's still a problem regarding inputting.

[https://github.com/StanleyW00/ip](url)

**Comment by skylee03** [comment]
I don't know what your input issue is, but I just tested your program on Linux. I tried adding some tasks and restarting your program, and the files can be loaded normally.

**Comment by skylee03** [comment]
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/24489025/dbdf5b89-c467-409d-8cf2-64d5ec7493b4)

**Comment by StanleyW00** [comment]
Thanks for testing my program! Regarding the problem, I was informed that my program has `java.util.NoSuchElementException` error for Mac and Linux. I noticed that the line that was referred to is where I tried to trim while calling the nextline method during inputting.

At least, I know that my program works on Linux.

**Comment by skylee03** [comment]
I think this exception is actually thrown by `nextLine()`. This problem occurs if the input stream has no new content but you still try to read from it. I'm not sure in what situation you encountered this problem, but at least I reproduced this problem in two cases:

1. Reads commands from a file, which does not contain `bye`.
2. Type <kbd>Ctrl</kbd> + <kbd>D</kbd> (or <kbd>Ctrl</kbd> + <kbd>Z</kbd> on Windows) at the command line to send an EOF character.

Generally, you don't need to worry about the above two special situations. If you really want to deal with this problem, you can use `hasNextLine()` to check whether the scanner has next line.

**Comment by skylee03** [comment]
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/24489025/9ae2c3bf-e4da-4a9d-bf14-8cd4f78667e1)

**Comment by StanleyW00** [comment]
I have added the part where it checks using `hasNextLine()`. See if it is fixes the problem that you mentioned.
