### ISSUE TITLE
Is there a settings for github for review before merging pull request.

### ISSUE THREAD

**Issue by yicheng-toh** [nus-cs2113-AY2324S1/forum#29]
Hi,

For the tp, during the tutorial exercise, I realised that I have accidentally merged my pull request to the team repo without waiting for any reviewers. Would it have any effect on the tp.

Moving forward, can I check if there is a way to prevent one from merging one's own pull request to the team repo. I would want to impose it on my account to prevent such situation from happening.

Thank you for your assistance and clarification.

**Comment by okkhoy** [comment]
What we recommend is documented here: https://nus-cs2113-ay2324s1.github.io/website/schedule/week8/project.html#tp-workflow

You can protect the master branch and set up rules requiring reviews before merging.
