### ISSUE TITLE
Peer Evaluation Last Question, no command given

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2113-AY2324S1/forum#31]
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/82555990/341a3b68-f7c2-4286-885a-91a73ef55f7b)
For this question, are we supposed to input nothing?

**Comment by okkhoy** [comment]
hmmm yes.. that was my miss. I have updated the question. Not sure if it reflects if you have already started the attempt.
the command to use is 

`foo 2`

**Comment by ziyi105** [comment]
hmm it doesnt, but the command is foo 2 right? I can see it on the second peer review survey
