### ISSUE TITLE
Week 7 Quiz Q4

### ISSUE THREAD

**Issue by skylee03** [nus-cs2113-AY2324S1/forum#33]
The question is:

> SLAP stands for Single Level of Abstraction Per method.

I think the answer is "false", because according to the [textbook](https://nus-cs2113-ay2324s1.github.io/website/se-book-adapted/chapters/codeQuality.html#slap-hard), "SLAP" stands for "Single Level of Abstraction Principle".

However, the expected answer is "true", and the explanation is:

> As per the textbook.

But when I used the textbook's search function to search for "Single Level of Abstraction Per method", no exact match was found.

**Comment by skylee03** [comment]
I checked the historical version of the course website and found that in [AY 2020-21](https://nus-cs2113-ay2021s1.github.io/website/se-book-adapted/chapters/codeQuality.html#slap-hard), it was indeed "Single Level of Abstraction Per method". However, as @ianyong [pointed out](https://github.com/se-edu/se-book/issues/101) its difference with the original expression in _The Productive Programmer_, the textbook for subsequent semesters has changed the expression to "Single Level of Abstraction Principle". I think the answer to the quiz should also be updated accordingly.

**Comment by okkhoy** [comment]
Hmmm... I remember updating this question just before the quiz was released ('cos we had a similar argument last semester). It looks like I didn't save it 🤦
