### ISSUE TITLE
Accessibility vs Visibility

### ISSUE THREAD

**Issue by skylee03** [nus-cs2113-AY2324S1/forum#36]
In Week 8 Quiz, the first question is:

> In the following class diagram, the ‘+’ and ‘-’ signs to indicate _accessibility_ of the attributes and the methods.
> ![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/24489025/d3c1e96e-fa06-4bd0-84fe-bdf0545252b9)

And the standard answer is:

> False. It’s called _visibility_, not _accessibility_.

I'm wondering if there are any differences between the two terms. As far as I know, they are often used interchangeably, and [The Java® Language Specification](https://docs.oracle.com/javase/specs/jls/se21/html/jls-6.html#jls-6.6) uses the term "accessibility".

**Comment by okkhoy** [comment]
As per the text:
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/1023494/5daca9cf-b8d8-4a17-a6e4-4a5f466a3561)

Some people do use it interchangeably; from UML perspective, visibility is more appropriate.

**Comment by skylee03** [comment]
I see. 

> As per the text: ![image](https://user-images.githubusercontent.com/1023494/275692516-5daca9cf-b8d8-4a17-a6e4-4a5f466a3561.png)
> 
> Some people do use it interchangeably; from UML perspective, visibility is more appropriate.

So "accessibility" and "visibility" refer to the same thing, except that the former is a Java term and the latter is a UML term?
