### ISSUE TITLE
Accidentally Finalized My Coding Exercise

### ISSUE THREAD

**Issue by skylee03** [nus-cs2113-AY2324S1/forum#4]
After attempted Q1, I found nowhere to proceed to the next question, so I finally clicked the "Finalize Submission" button by mistake. Now I can't move on to other questions.

**Comment by spaceman03** [comment]
I faced the same issue as OP too.

**Comment by woodenclock** [comment]
Me too, I faced the same problem, and only solved the first question.
Is there a way to revert my submission?

**Comment by okkhoy** [comment]
This is not a problem, I will revert it. However, @skylee03 @spaceman03  @woodenclock  please drop me a message (email/msteams) with your full names
