### ISSUE TITLE
CATcher dashboard update

### ISSUE THREAD

**Issue by bnjm2000** [nus-cs2113-AY2324S1/forum#48]
Hi, I had some issues with setting up CATcher last week. Not gonna lie, totally forgot about it until I received an email to set it up. I managed to get it set up with dummy issues yesterday. I would like to ask if it would show up updated on the individual tp dashboard or the participation dashboard that it was completed or if it would no longer be updated after the week is over. If yes, may I know what I did wrong that it is not updated to completed? If not, is there any way for me to know if I have done it correctly?

**Comment by okkhoy** [comment]
The dashboard won't update if the activity was completed after the deadline.
If you have the `alpa` repository created in your GitHub account, and has the issues you recorded on CATcher there you are OK.

**Comment by bnjm2000** [comment]
Resolved the issue, I misread the instructions and thought "from the application" referred to the mobile GitHub application. Resolved the issue by creating new issues from the CATcher application.
