### ISSUE TITLE
Weekly Programming Exercises Coding Standards

### ISSUE THREAD

**Issue by StanleyW00** [nus-cs2113-AY2324S1/forum#5]
In the programming exercises, are the coding standards graded as well?

**Comment by StanleyW00** [comment]
I have read the Grade Breakdown section from the website and I have found my answer.

**Comment by wendelinwemhoener** [comment]
So are they graded or not?

**Comment by StanleyW00** [comment]
From what I seen, It's not. However, I think it is a good habit to follow them.
