### ISSUE TITLE
What if the tester maliciously edit the data file and report it as a bug?

### ISSUE THREAD

**Issue by ziyi105** [nus-cs2113-AY2324S1/forum#53]
How can the developers proof innocent in this case?

**Comment by okkhoy** [comment]
Following this https://nus-cs2113-ay2324s1.github.io/website/admin/tp-constraints.html#constraint-human-editable-file it is a valid usecase.

**Comment by ziyi105** [comment]
Noted! But if the tester edit it on purpose such that it affects the output, how can the developers prove innocence?

**Comment by okkhoy** [comment]
You need to handle that when you are loading the data file.

**Comment by ziyi105** [comment]
If the tester add something in the data text file with correct formatting (e.g., add a new book A) after he exists the session, he restarts the application and list out a list of books which now contains bookA, and he reports it as a bug claiming that he didn't add book A in the previous session. Is this scenario possible and do we need to handle that?

**Comment by okkhoy** [comment]
😮  this can't be a bug. 

If the file is corrupted, you need to handle it.

If the file contains valid data and you are using it as a part of the data to load and show, it is the correct use case. It can't be called a bug when the product is handling new data correctly.

**Comment by ziyi105** [comment]
I see, thanks for the clarification prof!
