### ISSUE TITLE
Submission for documentation 

### ISSUE THREAD

**Issue by json-bot-boop** [nus-cs2113-AY2324S1/forum#55]
Is the submission due on Tue, Nov 14 13:00 or Mon, Nov 13 23:59?
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/33816512/7c1265bd-c844-40d7-89f3-f3a636579e56)

**Comment by okkhoy** [comment]
Errm.. the line in the text was a bug.
It is Nov 14 at 1 pm. I have fixed it just now.

Thanks for the catch!

**Comment by json-bot-boop** [comment]
sry for asking again, but is it 14 Nov, 1pm or 15 Nov, 1pm because the website shows this now.
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/33816512/e3188a9e-ba98-4b36-8d95-606f491549e7)

**Comment by okkhoy** [comment]
arrgh! this should be the most embarassing regressions!
Fixed now; please check
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/1023494/3fc7b00f-810a-4513-a398-68eb4fbf32ee)

**Comment by json-bot-boop** [comment]
yes, it is fixed.
