### ISSUE TITLE
Old exams to practice

### ISSUE THREAD

**Issue by wendelinwemhoener** [nus-cs2113-AY2324S1/forum#60]
Hey Prof, do you have any old exams you could give us to practice?

**Comment by okkhoy** [comment]
Will prepare a mock exam in a day/two and release.

**Comment by wendelinwemhoener** [comment]
The course website says the practice exam would be released one week before the actual exam. It is now Wednesday, our exam is on Tuesday, and the practice exam still hasn't been released
