### ISSUE TITLE
Clarification regarding PlantUML

### ISSUE THREAD

**Issue by Cazh1** [nus-cs2113-AY2324S1/forum#61]
1)
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/82131563/ceb48c6a-03fb-416b-82aa-2280ac7a99de)

Hi prof, can I double check with you if the coloured symbol notation to indicate private & public attributes are allowed as it was generated via plantUML when using "+" or "-".

2)
![image](https://github.com/nus-cs2113-AY2324S1/forum/assets/82131563/de2917ef-8036-4f02-9255-4668733a32e7)
The same question is for the symbols that was auto generated by PlantUML when creating the class diagram.

**Comment by DextheChik3n** [comment]
To add to the question, our team is [CS2113-T17-2]
the first one is related to issue #310
Link: https://github.com/nus-cs2113-AY2324S1/pe-dev-response/issues/310

while the second is related to issue #411
Link: https://github.com/nus-cs2113-AY2324S1/pe-dev-response/issues/411

**Comment by okkhoy** [comment]
1. no. it is non-standard notation.
you should disable them in plant-uml.

**Comment by DextheChik3n** [comment]
Alright understood, thanks prof. Akshay 🙏
