### ISSUE TITLE
Accuracy of bugs reporting due to 'incorrect' severity.

### ISSUE THREAD

**Issue by yicheng-toh** [nus-cs2113-AY2324S1/forum#64]
Hi Prof,

In the event that the tester report the bugs as serverity VeryLow but was accepted as serverity High by the dev team, is the accuracy of bug reporting for the tester affected? (assuming that the tester did not refute the decision by the dev team).

Should the tester be disagreeing? 

Thank you for the clarification.

**Comment by okkhoy** [comment]
😕 
Strange scenario! Up to the tester! I will refrain from suggesting anything

**Comment by yicheng-toh** [comment]
In that case, I guess the tester does get penalised for it and it is a trade off between severity High level bug and accuracy level. 

Thank you.
