### ISSUE TITLE
Disassociate iP/tP from their upstream repositories

### ISSUE THREAD

**Issue by skylee03** [nus-cs2113-AY2324S1/forum#65]
Today, the grades for the semester have been released, so we are now allowed to rename our repositories for the iP and tP. I am wondering that if we are also permitted to disassociate them from their upstream repositories and make them standalone?

- https://stackoverflow.com/questions/18390249/github-make-fork-an-own-project

**Comment by okkhoy** [comment]
Yup. You can evolve the project repositories any way you wish now.
