### ISSUE TITLE
Will there be a lecture (and tutorial) this Friday?

### ISSUE THREAD

**Issue by wendelinwemhoener** [nus-cs2113-AY2324S1/forum#9]
Friday (1 Sept) is Polling Day. Will there still be a lecture on Friday?
Also, what about the tutorial: If I am in a tutorial that is on Friday, will it take place or should I go to a tutorial on another day?

**Comment by skylee03** [comment]
Due to Sep 1 being declared as Polling Day and a public holiday, we will not have any tutorial or lecture on that day.

Akshay will work separately with the Friday teams offline on some administrative matters.

**Comment by okkhoy** [comment]
valid question, and @skylee03 haha! good answer 😜
